string = str(input("input your string "))
print(string[3-1])
print(string[1:])
print(string[:5])
print(string[:-2])
print(string[1::2])
print(string[1::1])
print(string[::-1])
print(string[-1::-2])
print(len(string))